name: run main.py

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '17 * * * *' # every hour at :17

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - run: python3 --version

      - name: Set up venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install uv

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Sync environment with uv
        run: |
          source .venv/bin/activate
          uv sync

      - name: Execute py script
        env:
          LOCATION: ${{ secrets.LOCATION }}
          NUMBER: ${{ secrets.NUMBER }}
          PASSPORT_NUMBER: ${{ secrets.PASSPORT_NUMBER }}
          SURNAME: ${{ secrets.SURNAME }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SMTP: ${{ secrets.SMTP }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          .venv/bin/uv run trigger.py

      - name: Upload status artifact
        uses: actions/upload-artifact@v4
        with:
          name: status-artifact
          path: status_record.json
